### ISSUE TITLE
【BUG】部分黑白图片导致致命错误

### ISSUE THREAD

**Issue by Phishion** [LanceGin/haishoku#8]
这个列表的所有图片都会出现错误，全部是黑白图片，但似乎不是所有黑白图片都会出现问题
All the pictures in this list will have errors, all black and white pictures, but it seems that not all black and white pictures will have problems.
`
image_list = ["https://store.playstation.com/store/api/chihiro/00_09_000/container/HK/ch/999/HP9000-CUSA02417_00-GONETOTHERAPTURE/1561603730000/image?w=432&h=432",
"https://store.playstation.com/store/api/chihiro/00_09_000/container/HK/ch/999/EP4034-CUSA03094_00-ASIA000000000000/1555304545000/image?w=432&h=432",
"https://store.playstation.com/store/api/chihiro/00_09_000/container/HK/ch/999/UP1164-CUSA13422_00-ASIA000000000000/1554792500000/image?w=432&h=432",
"https://store.playstation.com/store/api/chihiro/00_09_000/container/HK/ch/999/UP9000-CUSA00695_00-ASIAFULLGAME0000/1561601024000/image?w=432&h=432",
"https://store.playstation.com/store/api/chihiro/00_09_000/container/HK/ch/999/HP9000-CUSA12613_00-DEATHSTRAND00001/1561107092000/image?w=432&h=432",
"https://store.playstation.com/store/api/chihiro/00_09_000/container/HK/ch/999/HP2005-CUSA14358_00-PATOBOXASIA00000/1560504014000/image?w=432&h=432"]`

> Traceback (most recent call last):
  File "/Users/Phishion/Desktop/Haishokutest.py", line 12, in <module>
    dominant = Haishoku.getDominant(value)
  File "/usr/local/lib/python3.7/site-packages/haishoku/haishoku.py", line 119, in getDominant
    colors_mean = Haishoku.getColorsMean(image_path)
  File "/usr/local/lib/python3.7/site-packages/haishoku/haishoku.py", line 65, in getColorsMean
    grouped_image_colors = alg.group_by_accuracy(sorted_image_colors)
  File "/usr/local/lib/python3.7/site-packages/haishoku/alg.py", line 54, in group_by_accuracy
    rgb_maximum_json = rgb_maximum(sorted_tuple)
  File "/usr/local/lib/python3.7/site-packages/haishoku/alg.py", line 23, in rgb_maximum
    r_sorted_tuple = sorted(colors_tuple, key=lambda x:x[1][0])
  File "/usr/local/lib/python3.7/site-packages/haishoku/alg.py", line 23, in <lambda>
    r_sorted_tuple = sorted(colors_tuple, key=lambda x:x[1][0])
TypeError: 'int' object is not subscriptable

**Comment by LanceGin** [comment]
@Phishion 刚测试了一下，是因为提供的这些图片都是 灰度模式 导致，已经提交了一个新版本修复了这个问题，v1.1.8可以正常处理提供的这些图片

**Comment by Phishion** [comment]
感谢修复，我这边测试也正常了
