### ISSUE TITLE
input numpy array or PIL.Image rather than img_path

### ISSUE THREAD

**Issue by betterze** [LanceGin/haishoku#9]
Dear LanceGin,

Thank you for your wonderful work. I want to know if there is a way to input numpy array or PIL.Image rather than img_path? I already preprocess my images, I dont want to save one image to jpg then reload it.

Best Wishes,

Alex

**Comment by betterze** [comment]
And if it is poosible to use this package in PNG? Which mean I want to ignore some pixels when calculating palette? Thank you a lot for the help.

**Comment by pickanothername** [comment]
Workaround:
Add
```Python
class HaishokuFromImage(Haishoku):
    def __init__(self, image):
         self.image = image
```
to your project

**Comment by betterze** [comment]
cool, thx. I will try it.
